<h1 align='center'>Sanity Checks on API</h1>

<h4 align='center'>iReceptor $\mid$ Laura Gutierrez Funderburk $\mid$ November 19</h4>

<h4 align='center'>Supervised by Dr. Felix Breden, Dr. Jamie Scott, Dr. Brian Corrie</h4>

<h2 align='center'>Abstract</h2>

In this notebook I will parse and study JSON content found https://ipa.ireceptor.org/v2/samples with the purpose of doing sanity checks on data.

In [1]:
import requests
import json
import csv
import pandas as pd

/home/lgutierrezfunderburk/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

In [ ]:
!sh curlcom.sh

In [2]:
%run -i sanity_api.py

In [3]:
pandas_TSV = pd.read_csv("./Sequence_data_95_airrFormat.tsv",sep="\t")

In [4]:
# for item in pandas_TSV.columns:
#     print(item)

In [45]:
pandas_TSV.head()

,sequence,sequence_id,rearrangement_id,rev_comp,sequence_alignment,germline_alignment,v_call,j_call,d_call,c_call,...,study_description,lab_name,disease_state_sample,study_group_description,sample_id,template_class,tissue,cell_subset,sequencing_platform,cell_phenotype
0,ATTGTCCCTTGGGCCCAGATATCAGAAGCATCATCCAAGAAGTAAT...,ERR220436.8969 HQBD7YB07H0IFH length=305,NaN,False,NaN,NaN,"IGHV3-15*01, or IGHV3-15*02",IGHJ3*02,IGHD3-16*01,NaN,...,Cancer Study,The Wellcome Trust Sanger Institute,Chronic Lymphocytic Leukemia,Case,CLL_8_7,cDNA,PBMC,Mature B cell,454 GS FLX Titanium,NaN
1,ATTGTCCCTTGGGCCCAGATATCAGAAGCATCATCCAAGAAGTAAA...,ERR220436.4371 HQBD7YB07IICP6 length=316,NaN,False,NaN,NaN,"IGHV3-15*01, or IGHV3-15*02",IGHJ3*02,IGHD3-16*01,NaN,...,Cancer Study,The Wellcome Trust Sanger Institute,Chronic Lymphocytic Leukemia,Case,CLL_8_7,cDNA,PBMC,Mature B cell,454 GS FLX Titanium,NaN
2,CATTGTCCCTTGGGCCCAGATATCAGAAGCATCATCCAAGAAGTAA...,ERR220436.7968 HQBD7YB07ICTQD length=222,NaN,False,NaN,NaN,"IGHV3-15*01, or IGHV3-15*02, or IGHV3-15*07",IGHJ3*02,IGHD3-16*01,NaN,...,Cancer Study,The Wellcome Trust Sanger Institute,Chronic Lymphocytic Leukemia,Case,CLL_8_7,cDNA,PBMC,Mature B cell,454 GS FLX Titanium,NaN
3,ATTGTCCCTTGGGCCCAGATATCAGAAGCATCATCCAAGAAGTAAT...,ERR220436.8297 HQBD7YB07IODUR length=352,NaN,False,NaN,NaN,IGHV3-15*01,IGHJ3*02,IGHD3-16*01,NaN,...,Cancer Study,The Wellcome Trust Sanger Institute,Chronic Lymphocytic Leukemia,Case,CLL_8_7,cDNA,PBMC,Mature B cell,454 GS FLX Titanium,NaN
4,ATTGTCCCTTGGGCCCAGATATCAGAAGCATCATCCAAGAAGTAAT...,ERR220436.4137 HQBD7YB07ITB00 length=381,NaN,False,NaN,NaN,IGHV3-15*01,IGHJ3*02,IGHD3-16*01,NaN,...,Cancer Study,The Wellcome Trust Sanger Institute,Chronic Lymphocytic Leukemia,Case,CLL_8_7,cDNA,PBMC,Mature B cell,454 GS FLX Titanium,NaN

In [21]:
v_call = x_gene_array(pandas_TSV,"v_call")
#test_x_gene(v_call)
j_call = x_gene_array(pandas_TSV,"j_call")
#test_x_gene(j_call)
d_call = x_gene_array(pandas_TSV,"d_call")
#test_x_gene(d_call)

In [22]:
df2 = pd.DataFrame({"vcall":v_call,"jcall":j_call,"dcall":d_call})

In [23]:
jcal_s = IG_TR_Study(df2,"jcall")
vcal_s = IG_TR_Study(df2,"vcall")
dcal_s = IG_TR_Study(df2,"dcall")

In [24]:
thi_j = check_3_entry_gene(df2, "jcall")
thi_d = check_3_entry_gene(df2, "dcall")
thi_v = check_3_entry_gene(df2, "vcall")

In [25]:
test_df = pd.DataFrame({"vCallEntries":v_call,"jCallEntries":j_call,"dCallEntries":d_call,\
              'vCallStudy':vcal_s,'jCallStudy':jcal_s,'dCallStudy':dcal_s,\
              'vCall3char':thi_v,'jCall3char':thi_j,'dCall3char':thi_d })

In [44]:
test_df.head()

,vCallEntries,jCallEntries,dCallEntries,vCallStudy,jCallStudy,dCallStudy,vCall3char,jCall3char,dCall3char
0,"[IGHV3-15*01, IGHV3-15*02]",[IGHJ3*02],[IGHD3-16*01],{IG},{IG},{IG},{H},{H},{H}
1,"[IGHV3-15*01, IGHV3-15*02]",[IGHJ3*02],[IGHD3-16*01],{IG},{IG},{IG},{H},{H},{H}
2,"[IGHV3-15*01, IGHV3-15*02, IGHV3-15*07]",[IGHJ3*02],[IGHD3-16*01],{IG},{IG},{IG},{H},{H},{H}
3,[IGHV3-15*01],[IGHJ3*02],[IGHD3-16*01],{IG},{IG},{IG},{H},{H},{H}
4,[IGHV3-15*01],[IGHJ3*02],[IGHD3-16*01],{IG},{IG},{IG},{H},{H},{H}

In [42]:
summary_report(test_df,"vCallStudy","jCallStudy","dCallStudy")

[]

In [43]:
summary_report(test_df,"vCall3char","jCall3char","dCall3char")

[]

In [47]:
index_non_uniform = []
index_full = []
index_empty = []
for index, row in test_df.iterrows():
    if row["vCallStudy"]==set() and row["jCallStudy"]==set() and row["dCallStudy"]==set():
        index_empty.append(index)
    elif row["vCallStudy"]!=set() and row["jCallStudy"]!=set() and row["dCallStudy"]!=set():
        index_full.append(index)
    else:
        index_non_uniform.append(index)

pandas_TSV.iloc[index_empty,:].head()

,sequence,sequence_id,rearrangement_id,rev_comp,sequence_alignment,germline_alignment,v_call,j_call,d_call,c_call,...,study_description,lab_name,disease_state_sample,study_group_description,sample_id,template_class,tissue,cell_subset,sequencing_platform,cell_phenotype
110,CATTGTCCCTTGGGCCCAGATATCAGAAGCATCATCCAAGAAGTAA...,ERR220436.9497 HQBD7YB07IKB9R length=358,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Cancer Study,The Wellcome Trust Sanger Institute,Chronic Lymphocytic Leukemia,Case,CLL_8_7,cDNA,PBMC,Mature B cell,454 GS FLX Titanium,NaN
123,GTGGGGCAGGGGGGCTTCCAAGCCCAACAGGGCAGGACACACCAGA...,ERR220436.6426 HQBD7YB07IHTYD length=275,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Cancer Study,The Wellcome Trust Sanger Institute,Chronic Lymphocytic Leukemia,Case,CLL_8_7,cDNA,PBMC,Mature B cell,454 GS FLX Titanium,NaN
138,TGCAGCCTCTGGATTCTTTTTTCAGTGGCGCCTGGATGAGCTGGGT...,ERR220436.8947 HQBD7YB07H1GPF length=269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Cancer Study,The Wellcome Trust Sanger Institute,Chronic Lymphocytic Leukemia,Case,CLL_8_7,cDNA,PBMC,Mature B cell,454 GS FLX Titanium,NaN
188,ATTGTCCCTTGGGCCCAGATATCAGAAGCATCATCCAACGAAAGTA...,ERR220436.1273 HQBD7YB07IC9BG length=317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Cancer Study,The Wellcome Trust Sanger Institute,Chronic Lymphocytic Leukemia,Case,CLL_8_7,cDNA,PBMC,Mature B cell,454 GS FLX Titanium,NaN
218,TGCAGCCTCTGGATTCTTTTTCAGTGGCGCCTGGATGAGCTGGGTC...,ERR220436.9119 HQBD7YB07H3KOJ length=286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Cancer Study,The Wellcome Trust Sanger Institute,Chronic Lymphocytic Leukemia,Case,CLL_8_7,cDNA,PBMC,Mature B cell,454 GS FLX Titanium,NaN

In [48]:
test_df.iloc[index_full,:].head()

,vCallEntries,jCallEntries,dCallEntries,vCallStudy,jCallStudy,dCallStudy,vCall3char,jCall3char,dCall3char
0,"[IGHV3-15*01, IGHV3-15*02]",[IGHJ3*02],[IGHD3-16*01],{IG},{IG},{IG},{H},{H},{H}
1,"[IGHV3-15*01, IGHV3-15*02]",[IGHJ3*02],[IGHD3-16*01],{IG},{IG},{IG},{H},{H},{H}
2,"[IGHV3-15*01, IGHV3-15*02, IGHV3-15*07]",[IGHJ3*02],[IGHD3-16*01],{IG},{IG},{IG},{H},{H},{H}
3,[IGHV3-15*01],[IGHJ3*02],[IGHD3-16*01],{IG},{IG},{IG},{H},{H},{H}
4,[IGHV3-15*01],[IGHJ3*02],[IGHD3-16*01],{IG},{IG},{IG},{H},{H},{H}

In [49]:
test_df.iloc[index_non_uniform,:].head()

,vCallEntries,jCallEntries,dCallEntries,vCallStudy,jCallStudy,dCallStudy,vCall3char,jCall3char,dCall3char
8,"[IGHV3-15*01, IGHV3-15*02]",[IGHJ1*01],,{IG},{IG},{},{H},{H},{}
32,"[IGHV3-15*01, IGHV3-15*02]",[IGHJ1*01],,{IG},{IG},{},{H},{H},{}
34,"[IGHV3-15*01, IGHV3-15*02]",,,{IG},{},{},{H},{},{}
36,[IGHV3-15*04],,,{IG},{},{},{H},{},{}
37,"[IGHV3-15*01, IGHV3-15*02]",[IGHJ3*02],,{IG},{IG},{},{H},{H},{}

In [ ]:
# for index, row in test_df.iterrows()

In [ ]:
# DATA = json.loads(requests.get("https://ipa.ireceptor.org/v2/samples").text)
# df = pd.DataFrame.from_dict(DATA)

In [ ]:
# ids = [DATA[i]["_id"] for i in range(len(DATA))]
# ids

In [ ]:
# with open("id_run",'w') as f:
#     for item in ids:
#         f.write(str(item) + "\n")
# f.close()

In [ ]:
# Check_runID_in_SeqID = [False for item in seq_id if runID !=item.split(".")[0]]

In [ ]:
# Check_runID_in_SeqID